### ISSUE TITLE
java.lang.ClassCastException: Cannot cast akka.io.Tcp$CommandFailed to akka.io.Tcp$Bound

### ISSUE THREAD

**Issue by maasg** [NET-A-PORTER/pre-canned#9]
We are getting this exception from time to time when we are setting up the pre-canned server. Looks like it cannot bind, to it fails but the message is not being handled correctly.

Here's the full stack trace:

``` java
java.lang.ClassCastException: Cannot cast akka.io.Tcp$CommandFailed to akka.io.Tcp$Bound
    at java.lang.Class.cast(Class.java:3094)
    at scala.concurrent.Future$$anonfun$mapTo$1.apply(Future.scala:405)
    at scala.util.Success$$anonfun$map$1.apply(Try.scala:206)
    at scala.util.Try$.apply(Try.scala:161)
    at scala.util.Success.map(Try.scala:206)
    at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
    at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
    at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
    at scala.concurrent.Future$InternalCallbackExecutor$Batch$$anonfun$run$1.processBatch$1(Future.scala:643)
    at scala.concurrent.Future$InternalCallbackExecutor$Batch$$anonfun$run$1.apply$mcV$sp(Future.scala:658)
    at scala.concurrent.Future$InternalCallbackExecutor$Batch$$anonfun$run$1.apply(Future.scala:635)
    at scala.concurrent.Future$InternalCallbackExecutor$Batch$$anonfun$run$1.apply(Future.scala:635)
    at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
    at scala.concurrent.Future$InternalCallbackExecutor$Batch.run(Future.scala:634)
    at scala.concurrent.Future$InternalCallbackExecutor$.scala$concurrent$Future$InternalCallbackExecutor$$unbatchedExecute(Future.scala:694)
    at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:685)
    at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40)
    at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248)
    at akka.pattern.PromiseActorRef.$bang(AskSupport.scala:267)
    at spray.can.server.HttpListener$$anonfun$binding$1.applyOrElse(HttpListener.scala:60)
    at akka.actor.Actor$class.aroundReceive(Actor.scala:465)
    at spray.can.server.HttpListener.aroundReceive(HttpListener.scala:27)
    at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
    at akka.actor.ActorCell.invoke(ActorCell.scala:487)
    at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
    at akka.dispatch.Mailbox.run(Mailbox.scala:220)
    at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
    at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
    at ?.Given the api with akka config in 'test.conf' listening on port '7070'(features/devcluster.feature:7)
```

**Comment by theon** [comment]
Looks like there are multiple versions of spray on the classpath. I'll break out sbt-dependency-graph when I get a chance to see if precanned is causing it. It could also be two dependencies in your project that bring in different versions of spray.
